import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'

export const metadata = {
  title: 'Evolução Bike',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="overflow-y-scroll">
        <Navbar></Navbar>
        <main className="mt-10 sm:mt-28">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  )
}
